name: Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install required dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: flex libfl-dev bison yasm doxygen
          version: 1.0

      - name: Cache CDK and RTS
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/compiladores/root
          key: ${{ runner.os }}-20230513
      - name: Install CDK and RTS
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: /tmp
        run: |
          wget https://web.tecnico.ulisboa.pt/~david.matos/w/pt/images/c/c3/Libcdk19-202403010000.tar.bz2
          wget https://web.tecnico.ulisboa.pt/~david.matos/w/pt/images/b/be/Librts5-202103031636.tar.bz2
          tar xvf Libcdk19-202403010000.tar.bz2
          tar xvf Librts5-202103031636.tar.bz2
          cd Libcdk19-202403010000
          make install
          cd ..
          cd Librts5-202103031636
          make install
      - name: Compile project
        run: |
          make